
title = 'pubMLST TEST config'

bigsdb_instance = 'pubmlst'

['keys']
    CONSUMER_KEY = 'rUiQnMtLBZmCAEiCVFCEQeYu'
    CONSUMER_SECRET = 'W0cCia9SYtHD^hHtWEnQ1iw&!SGg7gdQc8HmHgoMEP'

['baseurls']
    REST_URL = 'http://rest.pubmlst.org/db/pubmlst_test_seqdef'
    WEB_URL = 'https://pubmlst.org/bigsdb?db=pubmlst_test_seqdef'

['routes']
    REQUEST_TOKEN_ROUTE = '/oauth/get_request_token'
    ACCESS_TOKEN_ROUTE = '/oauth/get_access_token'
    AUTHORIZE_ROUTE = '&page=authorizeClient'
    SESSION_TOKEN_ROUTE = '/oauth/get_session_token'